name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd android_app
          npm install

      - name: Build APK
        run: |
          cd android_app
          npx expo prebuild
          cd android
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: BlueGuyss-debug-apk
          path: android_app/android/app/build/outputs/apk/debug/app-debug.apk
